### ISSUE TITLE
2.4: Likert-kysymysten muokkaus/parannus

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#100]
Speksi:

Likert-kysymyksissä voi tällä hetkellä valita kultakin riviltä yhden vaihtoehdon. Kysymystyyppiä tulee kehittää siten, että jokaiselta riviltä voi valita useamman vaihtoehdon. Kysymystyyppiin tulee kehittää ”Rajoita vastauslukumäärää” -ominaisuus eli samanlainen ominaisuus kuin monivalintakysymyksissä tällä hetkellä on. Tällöin kyselyn tekijä voi määrittää, onko vastaajalla mahdollista valita kultakin riviltä yksi vai useampi vaihtoehto.

**Comment by ossitammi** [comment]
Huomiot: 

Isona työnä tähän liittyen tulisi olemaan CSV-tiedoston muokkaaminen soveltuvaksi uudentyyppiselle monivalintaiselle likertille, siten että nykyisten kyselyiden vastauksien lataaminen ei tästä kärsi. Toinen vaihtoehto olemassa olevan kysymystyypin muokkaukselle on luoda uusi kysymystyyppi “matriisikysymys” tms., joka toimisi kuten monivalintainen likert. Näissä toteutustavoissa on sama työmääräarvio. Mikäli tehdään kokonaan uusi kysymystyyppi, tulee tässä huomioida mobiilinäkymän tuki vastaavasti kuin toiminnallisuudessa 2.4: Likert-kysymyksen mobiilinäkymään vierityspalkki (alla)

**Comment by fercen** [comment]
UX-suositus: koska tällä hetkellä "Valintakysymys" ja "Monivalintakysymys" ovat erilliset kysymystyypit, myös yhden vaihtoehdon ja monen vaihtoehdon Likert-kysymysten tulisi säännönmukaisuuden nimissä olla erilliset kysymystyypit.

**Comment by ossitammi** [comment]
Huomiona:
Uusi kysymystyyppi tulee huomioida mm.
- Kyselyn käännöksissä (käännössivulla)
- Geopackagessa
- CSV-tiedostossa
- Sähköpostituksessa
- Mobiilinäkymässä
