### ISSUE TITLE
2.4: Ehdolliset kysymykset (ja sivut)

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#102]
Speksi:

Kyselyiden tekijöillä on tarve laatia vastaajille yksilöllisiä kysymyspolkuja. Tällä tarkoitetaan sitä, että vastaajalla näkyvät kysymykset riippuvat siitä, miten he ovat vastanneet aiempiin kysymyksiin.
Kyselyn laatija määrittelee seuraavaksi näkyvän kysymyksen tai kysymyssivun sen mukaan, miten vastaaja vastaa nykyiseen kysymykseen.

Seuraaville kysymystyypeille on mahdollista määrittää kysymyksen haarautuminen:

• valintakysymys
• monivalintakysymys
• numeerinen kysymys
• liukukytkinkysymys

Haarautumista ei tehdä karttakysymysten alikysymyksille.

Toimittajalta odotetaan ominaisuuden toteuttamisesta ehdotusta siitä, miten ehdolliset kysymykset toteutetaan kysymysten tekijöiden käyttöliittymässä. Teknisessä toteutuksessa on hyvä huomioida, että ehdollisia kysymyksiä voidaan jatkossa laajentaa muihin kysymystyyppeihin tulevaisuudessa.

**Comment by ossitammi** [comment]
Huomiot:

Kyselysivujen keskinäinen rakenne tulisi muuttaa lineaariseksi toiminnallisuuden myötä, jotta esimerkiksi pakollisten vastausten validointi selkeytyy. Tämä toiminnallisuus voisi olla syytä jakaa kahteen erilliseen konseptiin: ehdolliset kysymykset ja ehdolliset kysymyssivut. Molemmissa tarvitaan laajoja muutoksia kyselyjen tietomalliin sekä CSV-raportointiin. Ehdolliset kysymyssivut voisi toteuttaa alisivuina (esimerkiksi sivulta 2 haaraudutaan alisivulle 2a tai 2b vastauksen perusteella). Ehdollisten kysymysten ja sivujen olisi hyvä olla jollakin tapaa nähtävissä jo ennen ehdollisen vastauksen asettamista, jotta nämä eivät aiheuta saavutettavuudessa ongelmia, ja jotta käyttöliittymä pysyy staattisempana eikä uusia asioita ilmestyisi “tyhjästä”.

**Comment by jpeltzi** [comment]
Ehdollinen sivu voi esiintyä kyselyssä myöhempänäkin. Sekin toimii ylläpitopuolella paljolti normaalin sivun tavoin, mutta siinäkin on lisänä asetettavat ehdot kysymyssivun esittämiselle.
[Figma](https://www.figma.com/file/KoO6XJSVLdYZmrOgjYaaju/Fiilis?type=design&node-id=659-2414&mode=design&t=pyYvWkBlfHKT7Kc0-4)

![Image](https://github.com/Tampere/vuorovaikutusalusta/assets/5507205/06b3112c-b019-4a46-b588-fc6b6cfe40b4)
