### ISSUE TITLE
2.5: Kiitos-sivulle kuva

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#105]
Speksi:

Mahdollisuus lisätä Kiitos-sivulle kuva. Käyttöliittymässä kyselyn tekijän tulee voida kirjoittaa kuvalle alt-teksti. Kiitos-sivun voisi jatkossa tehdä joko ilman kuvaa tai kuvan kanssa. Jos käyttäjä lisää Kiitos-sivulle kuvan, asemoituu se kirjoitettujen tekstien alapuolelle ja keskelle sivua (ei logojen päälle). Esimerkiksi alla olevalla Kiitos-sivulla kuva sijoittuisi www.tampere.fi/nurmi-sorila -linkin alapuolelle:

![Image](https://github.com/Tampere/vuorovaikutusalusta/assets/15360748/b6e15d03-e271-49a4-b33e-54a068e27ad7)

**Comment by ossitammi** [comment]
Huomiot: Peltzin kanssa voisi käydä läpi tuleeko kuvan asettelussa huomioida kiitos-sivun designia suuremmin.

**Comment by mmoila** [comment]
Käytetään jo valmiiksi luotua komponenttia SurveyImageList pohjatoteutuksena. Kuvan lisäysmahdollisuus toteutetaan Kiitos-sivun alimmaksi komponentiksi. Muokataan komponenttia tukemaan vaihtoehtokuvauksia ja muokataan tekstejä tarpeen mukaan. Kuva tulostuu luonnollisessa koossaan, mutta korkeintaan 800 pikselin korkuisena.

**Comment by jpeltzi** [comment]
- Vaihtoehtokuvaukseksi on mahdollista tulostua "null". Tulee varmistaa, että attribuutti jää oikeasti tyhjäksi, jos kuvausta ei ole asetettu.
- Kuvan mitat olisi kiva voida ottaa mukaan merkintäkoodiin, jotta selain osaa varata sille sopivan tilan jo ennen, kuin kuva on latautunut. Tällöin muu sisältö ei joudu lennosta hyppelemään pois tieltä.
