### ISSUE TITLE
2.6: Vastausten lukumäärän esitys kyselyiden tekijöiden käyttöliittymässä

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#108]
Speksi:

Palataan.

**Comment by ossitammi** [comment]
Toteutusta varten poimitaan olemassa olevasta vastausnäkymästä ainakin seuraavat koodinpätkät:

- [ ]

**Comment by jpeltzi** [comment]
Käyttöliittymäsuunnitelma ylläpidon etusivulta: [Figma](https://www.figma.com/file/KoO6XJSVLdYZmrOgjYaaju/Fiilis?type=design&node-id=325-538&mode=design&t=55kAXBO6wR9GXICs-4)

- "Lataa vastaukset" -painike uudelleennimetään "Vastaukset"
- Vastausten lukumäärä ilmaistaan sulkeissa painikkeen sisällä, esim. "Vastaukset (1234)". Aiemmin keskusteltu kyltti/badge on vähän liian huomiota herättävä ratkaisu ja kutsuu käyttäjää tarpeettomasti toimimaan.

![Image](https://github.com/Tampere/vuorovaikutusalusta/assets/5507205/0f3a4bd9-8981-4644-95eb-27907c20c405)

**Comment by jpeltzi** [comment]
Vastausnäkymä rakentuu pikkuhiljaa tänne (vielä työversio, siksi ei liitekuvaa): [Figma](https://www.figma.com/file/KoO6XJSVLdYZmrOgjYaaju/Fiilis?type=design&node-id=335-1316&mode=design&t=55kAXBO6wR9GXICs-4)

**Comment by jpeltzi** [comment]
Vastausnäkymän käyttöliittymäsuunnitelma on valmistunut: [Figmaprototyyppi](https://www.figma.com/proto/KoO6XJSVLdYZmrOgjYaaju/Fiilis?page-id=409%3A1138&type=design&node-id=409-1159&viewport=1013%2C653%2C0.58&t=9DulAol8pHB6tMih-1&scaling=min-zoom&starting-point-node-id=409%3A1139&mode=design)

**Comment by ossitammi** [comment]
Yhteenvedon graafiin tulee histogrammeina kyselyyn päivittäin tulleiden submissioneiden lukumäärä. Ja jos vain onnistuu niin samaan graafiin voisi laittaa viivagraafina submissioneiden kumulativiinen summa.
