### ISSUE TITLE
2.6: Fiiliksen käyttöohje kyselyn tekijän käyttöliittymään

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#112]
Fiilis-työkalusta on laadittu käyttöohje kyselyiden tekijöiden käyttöön. Ohje on tällä hetkellä saatavissa Tampereen kaupungin intranetissä Taskussa. Ohje tulee tallentaa Fiilis-työkalun azure-resursseihin ja linkitetään sieltä suoraan kyselyiden tekijöiden käyttöliittymään, jotta ohje tulee paremmin kyselyiden tekijöiden käyttöön.

Ohje on pdf.-muotoinen ja linkki siihen tulee sijoittaa käyttöliittymän yläreunaan siniseen palkkiin kielivalinnan vasemmalle puolelle. Kun Ohje-painiketta klikkaa, ohjeen tulee aueta uuteen välilehteen.

Tampereen kaupungin työntekijöiden tulee voida tarvittaessa tallentaa muokattu käyttöohje kyselyiden tekijöiden käyttöliittymään. Käyttöohjeen tallentamisen tulee olla mahdollista samalla tavalla kuin Lisää vastausliite -osio toimii. Käyttöohjeen uuden version tallentaminen sijoitetaan aukeamaan profiili-ikoni-painikkeesta Kirjaudu ulos -toiminnon alapuolelle.

**Comment by ossitammi** [comment]
Huomiot:

Muutetaan kyselyn tietorakennetta sisältämään kyselyn käyttöohje. Käyttöohje voinee sijaita muiden jo tietokannassa olevien tiedostojen (liitteiden) kanssa samassa paikassa. Upload toiminnallisuus käyttöliittymän päivittämiseksi.

**Comment by jpeltzi** [comment]
Käyttöliittymäsuunnitelma uusien painikkeiden sijoittelusta.
Esitän, että samalla muutetaan käyttäjäikoni hammasratasikoniksi, koska käyttöohjeen päivitys ei sovi käyttäjäikonin asettamaan kontekstiin.
[Käyttöliittymäsuunnitelma](https://www.figma.com/file/KoO6XJSVLdYZmrOgjYaaju/Fiilis?type=design&node-id=138-6788&mode=design&t=mVZM1scCxPV3ALvX-4)
