### ISSUE TITLE
Kielikäännösten huomiot

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#166]
- [x] Käännösten kopiointi exceliin onnistui hyvin. Huomasin kuitenkin, että excelistä puuttui ainakin liukukytkin- ja likert-kysymyksen vaihtoehdot.

- [x] #176

**Comment by mmoila** [comment]
En saa jälkimmäistä ongelmaa toistettua. Täytyy kysellä siitä Teamsissa. Itselläni ei tunnukset vielä toimi.
