### ISSUE TITLE
Pitäisikö karttakysymyksen alikysymyksissä validointi tehdä vasta ok nappia painettaessa? Nyt virheilmoitus välähtelee ikävästi peruuta-nappia painettaessa tai klikattaessa ohi vastausvaihtoehdosta.

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#183]
Tämän hetkisen logiikan mukaan validointi suoritetaan kun kohdistus siirtyy (onBlur) alikysymyksestä toiseen elementtiin.

**Comment by jpeltzi** [comment]
Sanoisin, että riittää, jos validointi ohitetaan kun klikataan Peruuta-painiketta.
Suurin ongelma nykyisen toteutuksen kanssa on, että validointi suoritetaan heti, kun hiiri painuu pohjaan Peruuta-painikkeen päällä. Tämän myötä ilmestyvä virheviesti työntää lomakkeen sisältöä alemmas, mikä saattaa myös puskea klikatun Peruuta-painikkeen pois osoittimen alta, eikä painallus tällöin rekisteröidy.
Tämä saattaa antaa vaikutelman, että dialogista pääsisi pois peruuttamallakaan, jos kenttiä on täyttämättä.
