### ISSUE TITLE
Katselmoitava: Eri väriteemojen kontrastit

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#186]
Tarkistetaan vielä, että kaikilla valittavilla väriteemoilla kontrastierot ovat riittävät.

**Comment by jpeltzi** [comment]
Teemojen päävärien kontrasti on riittävä.
PS: Ne eivät tosin tarkoin vastaa ajantasaista Tampere.Finland-brändi-ilmettä.


![Image](https://github.com/Tampere/vuorovaikutusalusta/assets/5507205/0f908965-26f6-4ede-b453-3ca93a3473f3)
