### ISSUE TITLE
2.1: Näppäimistöselaus estetty

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#86]
Speksi:
Ks. Liite 1 Saavutettavuustestausraportti luku 4.1 (kuvaus ja vaikutus, ongelman ratkaisuvaihtoehtoja ja korjausehdotus, WCAG-onnistumiskriteerit).

Auditointiraportissa mainituista näppäimistöselaukseen liittyvistä havainnoista pyydetään tarjouspyyntö seuraavista kohdista:

• Järjestyskysymyksen alivalikoista valinta ruudunlukuohjelmilla
• Navigointipalkin käyttäminen näppäimistöllä
• Likert-kysymyksen sarakevaihtojen valinta näppäimistöllä
• Kartan lähentämis- ja loitontamissäätimen käyttö näppäimistöllä

**Comment by ossitammi** [comment]
Huomiot:
Järjestyskysymysten luominen valmiilla dnd -kirjastossa (esim. react beautiful dnd). Likert kysymysten kohdalla input-kenttien name -attribuuttiin arvo `question-id-${index}` tms. Tarkistetaan vielä oliko name -attribuutin selkokielisyydellä jotakin väliä. HUOM! Likertin sisällä span jonka sisällä radio-button, tämän sisälle generoituu aria-label={object object}, katsotaan mitä tuo on syönyt ja korjataan samalla. Luultavasti yrittää hakea kokonaisen käännösobjektin tekstinpätkän sijaan. Sivujen otsikoiden muuttaminen h2-tason otsikoiksi, siten että ne toimivat myös järkevästi linkkeinä. Kartan zoomauksen osalta luultavasti ainoa vaihtoehto on yrittää luoda Oskari-karttajulkaisun päälle omat nappulat lähentämiseen ja loitontamiseen, ja nämä nappulat ohjaavat Oskari-upotuksen zoomausta.

**Comment by jpeltzi** [comment]
Ainiin, täytyy vielä myös korjata kielivalinta, joka on myös näppäimistöestetty.

**Comment by jpeltzi** [comment]
Kielivalinnasta tehty PR #142 
Karttaupotteesta lohkaistu erillinen tiketti #143
