### ISSUE TITLE
2.1: Nimeämättömiä tai puutteellisesti nimettyjä painikkeita

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#87]
Speksi:
ks. Liite 1 Saavutettavuustestausraportti luku 4.2 (kuvaus ja vaikutus, korjausehdotus, WCAG-onnistumiskriteerit).

**Comment by ossitammi** [comment]
Huomiot:
Varmistetaan, että kaikki käyttöliittymän interaktiiviset komponentit kuvataan oikein interaktiivisten elementtien ominaisuuksissa, jotta tiedot välittyvät oikein eri avusteisille teknologioille. Kaikki avusteisten teknologioiden tarjoama informaatio perustuu HTML-koodissa olevaan tietoon, joten elementtien, komponenttien nimi, rooli ja arvo/tila tulee määritellä siellä.

**Comment by jpeltzi** [comment]
Kaikkien kysymystyyppien läpikäynti tehty, eikä puutteita enää löytynyt. Oletan korjaantuneen muiden tikettien myötä.

**Comment by jpeltzi** [comment]
Maria lupasi toimittaa Annanpuran luettelon nimeämättömistä painikkeista. Tarkistetaan se vielä, jahka saapuu.
