### ISSUE TITLE
2.1: Epätarkkaa otsikointia

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#88]
Speksi:

ks. Liite 1 Saavutettavuustestausraportti luku 4.3 (kuvaus ja vaikutus, korjausehdotus, WCAG-onnistumiskriteerit).
Kyselyn otsikointi tulee korjata seuraavalla tavalla:
• Kyselyn aloitussivun otsikko eli kyselyn nimi on h1-tason otsikko
• Kyselysivujen otsikot ovat h2-tason otsikoita
• Tekstiosion otsikko muutetaan h2-tason otsikosta h3-tason otsikoksi

Lisäksi toimittajalta pyydetään toteutusehdotusta siihen, miten jokaisella kyselysivulla esitettäisiin kyselyn nimi h1-tason otsikkona. Toteutusta voisi mahdollisuuksien mukaan miettiä siten, että kyselyn nimi tulisi automaattisesti sivuille h1-tason otsikkona.

**Comment by ossitammi** [comment]
Huomiot:

Kyselyyn lisätään koko kyselyn pääotsikko näkyville myös itse kysymyssivulle. Muokataan kysymyssivujen otsikot vastaamaan h2-tason otsikointia. Tekstiosioiden otsikot h3-tason otsikoiksi.

Liittyen toivottuun toiminnallisuuteen ehdollisista kysymyksistä, sekä yleisesti saavutettavuuden parantamiseksi, kyselysivujen välinen siirtymä olisi selkeintä muokata lineaariseksi, eli kyselysivujen välillä ei voisi enää navigoida. Tämä selkeyttäisi sovelluksen toimintaa, ja logiikka ehdollisten kysymysten suhteen olisi mutkattomampaa toteuttaa. Mikäli näin tehdään, voisi olla selkeintä, että kyselysivujen otsikot eivät toimi enää myöskään linkkeinä, vaan ne olisivat puhtaasti h2-tason otsikoita.

**Comment by jpeltzi** [comment]
Korjattu osana tikettiä #86 näppäimistöselailtavuuden parantamiseksi.
