### ISSUE TITLE
2.1: Nimeämättömiä lomakekenttiä

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#90]
Speksi:
ks. Liite 1 Saavutettavuustestausraportti luku 4.5 (kuvaus ja vaikutus, korjausehdotus, WCAG-onnistumiskriteerit).

**Comment by ossitammi** [comment]
Huomiot:
Sähköpostikenttään `name` atribuutti, arvoksi esim. "email". Kentän oheessa olevalta InputLabelilta puuttuu viittaus mihin kenttään se kohdistuu. Tarkastetaan että radiopainike jne. ryhmillä on <Fieldset> ja <Legend> tägit kuvaamassa, että ne ovat loogisia ryhmiään. Katsotaan `SurveyStepper`:n rivin ~324 fieldset -määritys mitä se on syönyt.

**Comment by jpeltzi** [comment]
WCAG-vaatimusten käyttämä termi "name" on erillinen HTML:n `name`-attribuutista, joten siihen ei ole tarpeen kajota. Myös selitteen viittaus on jo kunnossa; ehkä korjaantunut MUI:n versiopäivityksen myötä.
Tarkistan vielä kartta-alikysymykset...
