### ISSUE TITLE
2.1: Kyselyelementtien virheidenkäsittelyn ongelmia

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#91]
ks. Liite 1 Saavutettavuustestausraportti luku 4.6 (kuvaus ja vaikutus, korjausehdotus, WCAG-onnistumiskriteerit).

**Comment by ossitammi** [comment]
Huomiot:
Radiobuttien sisällä input kentän name -attribuuttiin generoituu arvo `[object Object]-group`. Korjataan tämä. Luultavasti yritetään päästä käsiksi kielikäännöksiin, mutta vahingossa ladataan kokonainen json -objekti itse tekstikäännöksen sijaan. Voisi olla hyvä jos kysellä ei pääse etenemään, ennen kuin kysymyssivun kaikkiin pakollisiin kysymyksiin on vastattu. Wräpätään kysymykset fieldsetin sisälle ja asetetaan kysymykselle (ehkäpä kysymyksen wräppäävälle FieldSetille?) kokonaisuudessa `aria-invalid = true`, jos pakollinen vastaus puuttuu.

**Comment by mmoila** [comment]
- [ ] Korjataan [object Object]-group -virhe
- [ ] Estetään kyselysivulla eteneminen, jos pakollisiin kysymyksiin ei ole vastattu. Kyselyssä pystyy jatkossa siirtymään eri sivujen välillä kronologisessa järjestyksessä ainoastaan "seuraava" ja "edellinen" -nappien avulla
- [ ] Wrapataan kysymykset fieldsetin sisään, jolle asetetaan ariva-invalid = true, jos pakollisiin kysymyksiin ei ole vastattu
- [ ] Virheilmoitus ("required") laukaistaan kun kohdistus siirtyy pakollisesta kysymyksestä johonkin toiseen komponenttiin

**Comment by ossitammi** [comment]
Katsotaan vielä, että aria-invalid -attribuutit eivät saa oletuksena `true` -arvoa.
