### ISSUE TITLE
2.1: Sivuston koodausongelmat

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#92]
ks. Liite 1 Saavutettavuustestausraportti luku 4.7 (kuvaus ja vaikutus, korjausehdotus, WCAG-onnistumiskriteerit).

**Comment by ossitammi** [comment]
Huomiot:
Käydään läpi `aria-describedby` -attribuutit ja katsotaan että näitä vastaava FormHelperText komponentti evaluoituu samoilla säännöillä. `${question.id}-required-text` arvo pitää ehkäpä siirtää itse komponenttien sisään SurveyQuestion -komponentin lopusta.

**Comment by mmoila** [comment]
- Tarkistetaan, että kaikki aria-describedby osoittavat olemassa olevaan komponenttiin
- Yhtenäistetään kysymysten labelit siten, että kysymyskomponentissa määritelty FormLabel viittaa aina olemassa olevaan id:seen
