### ISSUE TITLE
2.3: Kuvien tekstivastineista

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#95]
Speksi:
ks. Liite 1 Saavutettavuustestausraportti luku 6.1 (kuvaus ja vaikutus, korjausehdotus, WCAG-onnistumiskriteerit).
Pyydämme tarjousta seuraavan ongelman korjaukseen: Kyselysivun yleisenä taustakuvana vaihtuva kuva on yleisesti hyvin kuvailtu. Ongelmana on kuvan sijainti DOM-rajapinnassa, sillä elementti sijaitsee viimeisenä HTML-elementtinä jäsentelyssä ja siksi esimerkiksi ruudunlukuohjelmakäyttäjät eivät pääsääntöisesti löydä kyseistä kuvatekstiä.

**Comment by ossitammi** [comment]
Huomiot:
Lisätään kyselysivun otsikkoon sekä informatiiviseen kuvaan `aria-flowto` -attribuutti, sekä id, johon flow kohdistuu. Tällöin ruudunlukija lukee ensin kyselysivun otsikon, sen jälkeen luku kohdistuu oikean käden sivupalkin kuvaan (jos sellainen on olemassa), ja sieltä taas takaisin itse kyselyyn.

**Comment by mmoila** [comment]
Toteutettiin toiminnallisuus lisäämällä piilotettu kuva ennen kysymystä. `aria-flowto` -atribuuttia ei käytetty heikon tuettavuuden vuoksi.
