### ISSUE TITLE
2.3: Sekakielisyyttä

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#96]
Speksi:
ks. Liite 1 Saavutettavuustestausraportti luku 6.2 (kuvaus ja vaikutus, korjausehdotus, WCAG-onnistumiskriteerit).
Pyydämme tarjousta vain ei-Oskari-toteutuksesta tuleviin osiin.

**Comment by ossitammi** [comment]
Huomiot:
`aria-label`:t käydään läpi ja katsotaan että ne tulevat kielikäännöksistä.

**Comment by jpeltzi** [comment]
Karttakysymyksen kuvakepainikkeiden vaihtoehtokuvaukset ovat ristissä keskenään.
