### ISSUE TITLE
2.4: Kysymyksen tai muun osion kopioiminen

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#98]
Kyselyiden tekijöiden käyttöliittymässä tulee voida kopioida kysymys tai muu osio:

• Vaihtoehto 1: samassa kyselyssä mille tahansa sivulle eli joko samalle kysymyssivulle tai toiselle kysymyssivulle
• Vaihtoehto 2: toiseen kyselyyn. Kopioidun kysymyksen tulee sisältää kaikki samat ominaisuudet kuin se kysymys, joka kopioidaan. Kopioidussa kysymyksessä tulee säilyä alkuperäisen kysymyksen asetukset, esimerkiksi otsikko ja mahdolliset muut tekstit, pakollisuus, lisätiedot sekä merkkimäärä. Käännösten ei tule kopioitua.

Alempana taulukossa määritellyn ehdollisen kysymyksen kopiointi ja siitä riippuvien kysymysten kopiointi tulee tapahtua ilman haarautumisen huomiointia eli ehdollisen kysymyksen tulee kopioitua kuin se olisi tavallinen kysymys.

Mahdollisista kuvista ja liitteistä tulee tehdä kopiot eikä käyttää linkkejä alkuperäisen sivun kuviin ja liitteisiin (vrt. linuxin cp ja ln tai windowsin resurssien hallinnassa tiedoston kopiointi vs. linkki/.lnk).

**Comment by ossitammi** [comment]
Huomiot: 

Ehdotuksena käyttää leikepöytää tässä hyödyksi, jolloin osion kopioiminen muihin kyselyihin onnistuisi yhtä helposti kuin kopiointi lähtökyselyn sisällä. Leikepöydän käyttäminen kopioinnissa kattaisi siis molemmat tarjouspyynnössä esitetyt vaihtoehdot.

**Comment by jpeltzi** [comment]
[Käyttöliittymäsuunnitelma](https://www.figma.com/file/KoO6XJSVLdYZmrOgjYaaju/Fiilis?type=design&node-id=216-4332&mode=dev)
