### ISSUE TITLE
2.4: Kysymyssivun kopioiminen uuden kysymyssivun pohjaksi

### ISSUE THREAD

**Issue by ossitammi** [Tampere/vuorovaikutusalusta#99]
Kyselyiden tekijöiden käyttöliittymässä tulee olla mahdollista kopioida koko kysymyssivu uuden kysymyssivun pohjaksi. Kaikkien kysymyssivun asetusten tulee säilyä kopioinnissa.

Kopioidun sivun tulee sisältää kopioitavalta sivulta myös oikean sivupalstan sisältö eli kartta, kuva tai ”ei mitään” sekä sivulla näytettävät karttatasot. Eli Näytettävät karttatasot -valintojen tulee säilyä, kun kysymyssivu kopioidaan. Lisäksi kopioitavan kysymyssivun vasemmanpuoleisen sivupalstan kaiken sisällön, esimerkiksi kysymysten, tekstien, kuvien ja liitteiden tulee kopioitua. Kysymysten ominaisuuksien (esim. pakollisuus, lisätiedot, merkkimäärä) tulee säilyä sivua
kopioitaessa. Käännösten ei tule kopioitua.

**Comment by ossitammi** [comment]
Huomiot:

Ehdotuksena käyttää leikepöytää tässä hyödyksi, jolloin osion kopioiminen muihin kyselyihin onnistuisi yhtä helposti kuin kopiointi lähtökyselyn sisällä. Leikepöydän käyttäminen kopioinnissa kattaisi siis molemmat tarjouspyynnössä esitetyt vaihtoehdot.

**Comment by jpeltzi** [comment]
[Käyttöliittymäsuunnitelma](https://www.figma.com/file/KoO6XJSVLdYZmrOgjYaaju/Fiilis?type=design&node-id=216-4344&mode=dev)
